version: 2
jobs:
  build:
    docker:
      - image: 'cimg/node:19.8.0'
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: release
          command: npm run semantic-release || true
